  version: '3.8'
services:
  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
  mongo:
    image: mongo
    ports:
      - "27017:27017"
